[tox]
requires =
    tox>=4
env_list = 
    py{310,311}-django{50,51,52,60}
    py{312,313}-django{50,51,52,60,61}

[testenv]
description = run unit tests
deps=
    django61: Django>=6.1,<6.2
    django60: Django>=6.0,<6.1
    django52: Django>=5.2,<5.3
    django51: Django>=5.1,<5.2
    django50: Django>=5.0,<5.1
    -r.requirements/dev.txt

setenv =
    PYTHONPATH = {toxinidir}
commands_pre =
    playwright install
commands =
    python manage.py test {posargs}

