# Generated by Django 4.1 on 2023-06-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mptt2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mptt_lft', models.PositiveIntegerField(editable=False, help_text='The left value of the node', verbose_name='left')),
                ('mptt_rgt', models.PositiveIntegerField(editable=False, help_text='The right value of the node', verbose_name='right')),
                ('mptt_depth', models.PositiveIntegerField(editable=False, help_text='The hierarchy level of this node inside the tree', verbose_name='depth')),
                ('mptt_parent', models.ForeignKey(editable=False, help_text='The parent of this node', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chilren', related_query_name='child', to='tests.simplenode', verbose_name='parent')),
                ('mptt_tree', models.ForeignKey(help_text='The unique tree, where this node is part of', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', related_query_name='node', to='mptt2.tree', verbose_name='tree')),
            ],
            options={
                'ordering': ['mptt_tree_id', 'mptt_lft'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='simplenode',
            index=models.Index(fields=['mptt_tree_id', 'mptt_lft', 'mptt_rgt'], name='tests_simpl_mptt_tr_ce9f69_idx'),
        ),
        migrations.AddConstraint(
            model_name='simplenode',
            constraint=models.CheckConstraint(check=models.Q(('mptt_rgt__gt', models.F('mptt_lft'))), name='rgt_gt_lft', violation_error_message='The right side value rgt is allways greater than the node left side value lft.'),
        ),
    ]
