# Generated by Django 5.2 on 2026-09-04 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mptt2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mptt_lft', models.PositiveIntegerField(editable=False, help_text='The left value of the node', verbose_name='left')),
                ('mptt_rgt', models.PositiveIntegerField(editable=False, help_text='The right value of the node', verbose_name='right')),
                ('mptt_depth', models.PositiveIntegerField(editable=False, help_text='The hierarchy level of this node inside the tree', verbose_name='depth')),
                ('title', models.CharField(default='some node', max_length=10)),
                ('mptt_parent', models.ForeignKey(editable=False, help_text='The parent of this node', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chilren', related_query_name='child', to='tests.othernode', verbose_name='parent')),
                ('mptt_tree', models.ForeignKey(editable=False, help_text='The unique tree, where this node is part of', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_nodes', related_query_name='%(app_label)s_%(class)s_node', to='mptt2.tree', verbose_name='tree')),
            ],
            options={
                'ordering': ['mptt_tree_id', 'mptt_lft'],
                'abstract': False,
                'indexes': [models.Index(fields=['mptt_tree_id', 'mptt_lft', 'mptt_rgt'], name='tests_other_mptt_tr_0acc71_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('mptt_rgt__gt', models.F('mptt_lft'))), name='tests_othernode_rgt_gt_lft')],
            },
        ),
        migrations.CreateModel(
            name='SimpleNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mptt_lft', models.PositiveIntegerField(editable=False, help_text='The left value of the node', verbose_name='left')),
                ('mptt_rgt', models.PositiveIntegerField(editable=False, help_text='The right value of the node', verbose_name='right')),
                ('mptt_depth', models.PositiveIntegerField(editable=False, help_text='The hierarchy level of this node inside the tree', verbose_name='depth')),
                ('title', models.CharField(default='some node', max_length=10)),
                ('mptt_parent', models.ForeignKey(editable=False, help_text='The parent of this node', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chilren', related_query_name='child', to='tests.simplenode', verbose_name='parent')),
                ('mptt_tree', models.ForeignKey(editable=False, help_text='The unique tree, where this node is part of', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_nodes', related_query_name='%(app_label)s_%(class)s_node', to='mptt2.tree', verbose_name='tree')),
            ],
            options={
                'ordering': ['mptt_tree_id', 'mptt_lft'],
                'abstract': False,
                'indexes': [models.Index(fields=['mptt_tree_id', 'mptt_lft', 'mptt_rgt'], name='tests_simpl_mptt_tr_ce9f69_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('mptt_rgt__gt', models.F('mptt_lft'))), name='tests_simplenode_rgt_gt_lft')],
            },
        ),
    ]
