# Generated by Django 4.2 on 2023-06-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_simplenode_mptt_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplenode',
            name='title',
            field=models.CharField(default='some node', max_length=10),
        ),
    ]
